import DISPATCH_CONSTANTS_TYPE_MODEL from "./dispatch-constant-model";

const DISPATCH_CONSTANTS: DISPATCH_CONSTANTS_TYPE_MODEL = {
  APP: {
    INITIALIZE_SUCCESS: 'INITIALIZE_SUCCESS',
  },

  PRELOADER: {
    SET_IS_FETCHING: 'SET_IS_FETCHING',
  },

  AUTH: {
    SET_AUTH_DATA: 'SET_AUTH_DATA',
    IS_REMEMBER_ME: 'IS_REMEMBER_ME',
    LOG_OUT: 'LOG_OUT',
  },

  SIDE_BAR:{
    SET_FRIENDS: 'SET_FRIENDS',
  },

  PROFILE_PAGE: {
    SET_PROFILE: 'SET_PROFILE',
    SET_PROFILE_POSTS: 'SET_PROFILE_POSTS',
    SET_META_DATA: 'SET_META_DATA',
  },

  DIALOG_PAGE: {
    SEND_MESSAGE: 'SEND_MESSAGE',
    SET_DIALOGS: 'SET_DIALOGS',
    SET_DIALOG: 'SET_DIALOG',
    SET_DIALOGS_META_DATA: 'SET_DIALOGS_META_DATA',
  },

  USERS_PAGE: {
    SET_USERS: 'SET_USERS',
    SET_META_DATA: 'SET_META_DATA',
    FOLLOW: 'FOLLOW',
    UNFOLLOW: 'UNFOLLOW',
    CHANGE_DISPLAY_USERS: 'CHANGE_DISPLAY_USERS',
    SET_ACTIVE_PAGE: 'SET_ACTIVE_PAGE',
    FOLLOWING_IN_PROGRESS: 'FOLLOWING_IN_PROGRESS',
  },

  MUSIC_PAGE: {
    SET_MUSICS: "SET_MUSICS",
    SET_MUSICS_META_DATA: 'SET_MUSICS_META_DATA',
  },
}

export default DISPATCH_CONSTANTS;